CREATE TABLE Customer ( 
    userId INT PRIMARY KEY AUTO_INCREMENT, 
    fName VARCHAR(300) NOT NULL, 
    lName VARCHAR(300) NOT NULL, 
    email  VARCHAR(300) NOT NULL UNIQUE, 
    userPassword VARCHAR(300) NOT NULL );