CREATE TABLE Customer ( 
    UserId INT PRIMARY KEY AUTO_INCREMENT, 
    FName VARCHAR(300) NOT NULL, 
    LName VARCHAR(300) NOT NULL, 
    Email  VARCHAR(300) NOT NULL UNIQUE, 
    UserPassword VARCHAR(300) NOT NULL );